set nocompatible               " be iMproved
filetype off                   " required for Vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-fugitive'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'altercation/vim-colors-solarized'
" vim-scripts repos
Bundle 'pyflakes.vim'
Bundle 'python.vim'
Bundle 'indentpython.vim'
" non github repos
Bundle 'git://git.wincent.com/command-t.git'

filetype plugin indent on     " required for vundle


"turn on status line
set laststatus=2
"adapted from tpope
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y%{fugitive#statusline()}%#ErrorMsg#%*%=%-14.(%l,%c%V%)\ %P


"set good PEP-8 defaults. 
"TODO: make this only apply to python files
setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal smarttab
setlocal expandtab

set incsearch
set hlsearch
set ignorecase
set smartcase

" Highlight whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

let mapleader=","


if &t_Co >= 256 || has("gui_running")
   set background=dark
   colorscheme solarized
   "colorscheme molokai
   set guifont=Terminus\ 18
endif

if &t_Co > 2 || has("gui_running")
   " switch syntax highlighting on, when the terminal has colors
   syntax on
endif
